services:
  postgres:
    image: postgres:16.1-alpine
    container_name: crossflow_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - crossflow_network

  server:
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile
    container_name: crossflow_server
    environment:
      - NODE_ENV=development
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=root
      - PG_DATABASE=mydb
      - PORT=5000
    ports:
      - '5000:5000'
    depends_on:
      - postgres
    networks:
      - crossflow_network
    volumes:
      - ./packages/server:/app
      - /app/node_modules

networks:
  crossflow_network:
    driver: bridge

volumes:
  postgres_data:
